# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaffoldrigidalignerwidget.ui'
#
# Created: Fri Jun 21 07:42:37 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScaffoldRigidAlignerWidget(object):
    def setupUi(self, ScaffoldRigidAlignerWidget, shared_opengl_context):
        ScaffoldRigidAlignerWidget.setObjectName("ScaffoldRigidAlignerWidget")
        ScaffoldRigidAlignerWidget.resize(1698, 902)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScaffoldRigidAlignerWidget.sizePolicy().hasHeightForWidth())
        ScaffoldRigidAlignerWidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(ScaffoldRigidAlignerWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(ScaffoldRigidAlignerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(418, 135))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 416, 860))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.alignPage = QtGui.QWidget()
        self.alignPage.setGeometry(QtCore.QRect(0, 0, 412, 796))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignPage.sizePolicy().hasHeightForWidth())
        self.alignPage.setSizePolicy(sizePolicy)
        self.alignPage.setObjectName("alignPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.alignPage)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.alignSettingsGroupBox = QtGui.QGroupBox(self.alignPage)
        self.alignSettingsGroupBox.setTitle("")
        self.alignSettingsGroupBox.setObjectName("alignSettingsGroupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.alignSettingsGroupBox)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ifTime_frame = QtGui.QFrame(self.alignSettingsGroupBox)
        self.ifTime_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ifTime_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.ifTime_frame.setObjectName("ifTime_frame")
        self.gridLayout_8 = QtGui.QGridLayout(self.ifTime_frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.timeData_label = QtGui.QLabel(self.ifTime_frame)
        self.timeData_label.setObjectName("timeData_label")
        self.gridLayout_8.addWidget(self.timeData_label, 0, 0, 1, 1)
        self.timeNo_radioButton = QtGui.QRadioButton(self.ifTime_frame)
        self.timeNo_radioButton.setObjectName("timeNo_radioButton")
        self.gridLayout_8.addWidget(self.timeNo_radioButton, 0, 1, 1, 1)
        self.timeYes_radioButton = QtGui.QRadioButton(self.ifTime_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeYes_radioButton.sizePolicy().hasHeightForWidth())
        self.timeYes_radioButton.setSizePolicy(sizePolicy)
        self.timeYes_radioButton.setObjectName("timeYes_radioButton")
        self.gridLayout_8.addWidget(self.timeYes_radioButton, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 17, 0, 1, 1)
        self.timePoint_spinBox = QtGui.QSpinBox(self.ifTime_frame)
        self.timePoint_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timePoint_spinBox.sizePolicy().hasHeightForWidth())
        self.timePoint_spinBox.setSizePolicy(sizePolicy)
        self.timePoint_spinBox.setMaximum(1000000000)
        self.timePoint_spinBox.setObjectName("timePoint_spinBox")
        self.gridLayout_8.addWidget(self.timePoint_spinBox, 17, 3, 1, 1)
        self.timePoint_label = QtGui.QLabel(self.ifTime_frame)
        self.timePoint_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timePoint_label.sizePolicy().hasHeightForWidth())
        self.timePoint_label.setSizePolicy(sizePolicy)
        self.timePoint_label.setObjectName("timePoint_label")
        self.gridLayout_8.addWidget(self.timePoint_label, 17, 2, 1, 1)
        self.timeSkip_pushButton = QtGui.QPushButton(self.ifTime_frame)
        self.timeSkip_pushButton.setEnabled(False)
        self.timeSkip_pushButton.setObjectName("timeSkip_pushButton")
        self.gridLayout_8.addWidget(self.timeSkip_pushButton, 3, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.ifTime_frame)
        self.partial_frame = QtGui.QFrame(self.alignSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partial_frame.sizePolicy().hasHeightForWidth())
        self.partial_frame.setSizePolicy(sizePolicy)
        self.partial_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.partial_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.partial_frame.setObjectName("partial_frame")
        self.gridLayout_7 = QtGui.QGridLayout(self.partial_frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.partialZ_lineEdit = QtGui.QLineEdit(self.partial_frame)
        self.partialZ_lineEdit.setEnabled(False)
        self.partialZ_lineEdit.setObjectName("partialZ_lineEdit")
        self.gridLayout_7.addWidget(self.partialZ_lineEdit, 1, 7, 1, 1)
        self.partialY_label = QtGui.QLabel(self.partial_frame)
        self.partialY_label.setObjectName("partialY_label")
        self.gridLayout_7.addWidget(self.partialY_label, 2, 5, 1, 1)
        self.partialX_label = QtGui.QLabel(self.partial_frame)
        self.partialX_label.setObjectName("partialX_label")
        self.gridLayout_7.addWidget(self.partialX_label, 3, 5, 1, 1)
        self.partialXlineEdit = QtGui.QLineEdit(self.partial_frame)
        self.partialXlineEdit.setEnabled(False)
        self.partialXlineEdit.setObjectName("partialXlineEdit")
        self.gridLayout_7.addWidget(self.partialXlineEdit, 3, 7, 1, 1)
        self.partial_label = QtGui.QLabel(self.partial_frame)
        self.partial_label.setObjectName("partial_label")
        self.gridLayout_7.addWidget(self.partial_label, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 2, 3, 1, 1)
        self.partialY_lineEdit = QtGui.QLineEdit(self.partial_frame)
        self.partialY_lineEdit.setEnabled(False)
        self.partialY_lineEdit.setObjectName("partialY_lineEdit")
        self.gridLayout_7.addWidget(self.partialY_lineEdit, 2, 7, 1, 1)
        self.partialZ_label = QtGui.QLabel(self.partial_frame)
        self.partialZ_label.setObjectName("partialZ_label")
        self.gridLayout_7.addWidget(self.partialZ_label, 1, 5, 1, 1)
        self.partialData_checkBox = QtGui.QCheckBox(self.partial_frame)
        self.partialData_checkBox.setText("")
        self.partialData_checkBox.setObjectName("partialData_checkBox")
        self.gridLayout_7.addWidget(self.partialData_checkBox, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 2, 4, 1, 1)
        self.visualAid_checkBox = QtGui.QCheckBox(self.partial_frame)
        self.visualAid_checkBox.setEnabled(False)
        self.visualAid_checkBox.setObjectName("visualAid_checkBox")
        self.gridLayout_7.addWidget(self.visualAid_checkBox, 4, 7, 1, 1)
        self.verticalLayout_7.addWidget(self.partial_frame)
        self.scaffoldAxis_frame = QtGui.QFrame(self.alignSettingsGroupBox)
        self.scaffoldAxis_frame.setMinimumSize(QtCore.QSize(0, 10))
        self.scaffoldAxis_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scaffoldAxis_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.scaffoldAxis_frame.setObjectName("scaffoldAxis_frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.scaffoldAxis_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scaffoldY_radioButton = QtGui.QRadioButton(self.scaffoldAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaffoldY_radioButton.sizePolicy().hasHeightForWidth())
        self.scaffoldY_radioButton.setSizePolicy(sizePolicy)
        self.scaffoldY_radioButton.setObjectName("scaffoldY_radioButton")
        self.gridLayout_2.addWidget(self.scaffoldY_radioButton, 0, 2, 1, 1)
        self.scaffoldAxis_label = QtGui.QLabel(self.scaffoldAxis_frame)
        self.scaffoldAxis_label.setCursor(QtCore.Qt.ArrowCursor)
        self.scaffoldAxis_label.setObjectName("scaffoldAxis_label")
        self.gridLayout_2.addWidget(self.scaffoldAxis_label, 0, 0, 1, 1)
        self.scaffoldZ_radioButton = QtGui.QRadioButton(self.scaffoldAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaffoldZ_radioButton.sizePolicy().hasHeightForWidth())
        self.scaffoldZ_radioButton.setSizePolicy(sizePolicy)
        self.scaffoldZ_radioButton.setObjectName("scaffoldZ_radioButton")
        self.gridLayout_2.addWidget(self.scaffoldZ_radioButton, 0, 1, 1, 1)
        self.scaffoldX_radioButton = QtGui.QRadioButton(self.scaffoldAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaffoldX_radioButton.sizePolicy().hasHeightForWidth())
        self.scaffoldX_radioButton.setSizePolicy(sizePolicy)
        self.scaffoldX_radioButton.setObjectName("scaffoldX_radioButton")
        self.gridLayout_2.addWidget(self.scaffoldX_radioButton, 0, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.scaffoldAxis_frame)
        self.dataAxis_frame = QtGui.QFrame(self.alignSettingsGroupBox)
        self.dataAxis_frame.setMinimumSize(QtCore.QSize(0, 10))
        self.dataAxis_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.dataAxis_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.dataAxis_frame.setObjectName("dataAxis_frame")
        self.gridLayout_3 = QtGui.QGridLayout(self.dataAxis_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dataZ_radioButton = QtGui.QRadioButton(self.dataAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataZ_radioButton.sizePolicy().hasHeightForWidth())
        self.dataZ_radioButton.setSizePolicy(sizePolicy)
        self.dataZ_radioButton.setObjectName("dataZ_radioButton")
        self.gridLayout_3.addWidget(self.dataZ_radioButton, 2, 1, 1, 1)
        self.datadY_radioButton = QtGui.QRadioButton(self.dataAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datadY_radioButton.sizePolicy().hasHeightForWidth())
        self.datadY_radioButton.setSizePolicy(sizePolicy)
        self.datadY_radioButton.setObjectName("datadY_radioButton")
        self.gridLayout_3.addWidget(self.datadY_radioButton, 2, 2, 1, 1)
        self.dataAxis_label = QtGui.QLabel(self.dataAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataAxis_label.sizePolicy().hasHeightForWidth())
        self.dataAxis_label.setSizePolicy(sizePolicy)
        self.dataAxis_label.setObjectName("dataAxis_label")
        self.gridLayout_3.addWidget(self.dataAxis_label, 2, 0, 1, 1)
        self.dataX_radioButton = QtGui.QRadioButton(self.dataAxis_frame)
        self.dataX_radioButton.setObjectName("dataX_radioButton")
        self.gridLayout_3.addWidget(self.dataX_radioButton, 2, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.dataAxis_frame)
        self.swapAxis_frame = QtGui.QFrame(self.alignSettingsGroupBox)
        self.swapAxis_frame.setMinimumSize(QtCore.QSize(0, 59))
        self.swapAxis_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.swapAxis_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.swapAxis_frame.setObjectName("swapAxis_frame")
        self.gridLayout_6 = QtGui.QGridLayout(self.swapAxis_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem3, 7, 0, 1, 1)
        self.yaw_label = QtGui.QLabel(self.swapAxis_frame)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout_6.addWidget(self.yaw_label, 8, 2, 1, 1)
        self.roll_label = QtGui.QLabel(self.swapAxis_frame)
        self.roll_label.setObjectName("roll_label")
        self.gridLayout_6.addWidget(self.roll_label, 8, 4, 1, 1)
        self.axisDone_pushButton = QtGui.QPushButton(self.swapAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axisDone_pushButton.sizePolicy().hasHeightForWidth())
        self.axisDone_pushButton.setSizePolicy(sizePolicy)
        self.axisDone_pushButton.setObjectName("axisDone_pushButton")
        self.gridLayout_6.addWidget(self.axisDone_pushButton, 6, 0, 1, 1)
        self.pitch_doubleSpinBox = QtGui.QDoubleSpinBox(self.swapAxis_frame)
        self.pitch_doubleSpinBox.setMinimum(-180.0)
        self.pitch_doubleSpinBox.setMaximum(180.0)
        self.pitch_doubleSpinBox.setObjectName("pitch_doubleSpinBox")
        self.gridLayout_6.addWidget(self.pitch_doubleSpinBox, 9, 3, 1, 1)
        self.yaw_doubleSpinBox = QtGui.QDoubleSpinBox(self.swapAxis_frame)
        self.yaw_doubleSpinBox.setMinimum(-180.0)
        self.yaw_doubleSpinBox.setMaximum(180.0)
        self.yaw_doubleSpinBox.setObjectName("yaw_doubleSpinBox")
        self.gridLayout_6.addWidget(self.yaw_doubleSpinBox, 9, 2, 1, 1)
        self.upsideDown_checkBox = QtGui.QCheckBox(self.swapAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upsideDown_checkBox.sizePolicy().hasHeightForWidth())
        self.upsideDown_checkBox.setSizePolicy(sizePolicy)
        self.upsideDown_checkBox.setObjectName("upsideDown_checkBox")
        self.gridLayout_6.addWidget(self.upsideDown_checkBox, 3, 1, 1, 1)
        self.rotateAxis_label = QtGui.QLabel(self.swapAxis_frame)
        self.rotateAxis_label.setObjectName("rotateAxis_label")
        self.gridLayout_6.addWidget(self.rotateAxis_label, 8, 0, 1, 1)
        self.roll_doubleSpinBox = QtGui.QDoubleSpinBox(self.swapAxis_frame)
        self.roll_doubleSpinBox.setMinimum(-180.0)
        self.roll_doubleSpinBox.setMaximum(180.0)
        self.roll_doubleSpinBox.setObjectName("roll_doubleSpinBox")
        self.gridLayout_6.addWidget(self.roll_doubleSpinBox, 9, 4, 1, 1)
        self.upsideDown_label = QtGui.QLabel(self.swapAxis_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upsideDown_label.sizePolicy().hasHeightForWidth())
        self.upsideDown_label.setSizePolicy(sizePolicy)
        self.upsideDown_label.setObjectName("upsideDown_label")
        self.gridLayout_6.addWidget(self.upsideDown_label, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem4, 11, 1, 1, 1)
        self.pitch_label = QtGui.QLabel(self.swapAxis_frame)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout_6.addWidget(self.pitch_label, 8, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 5, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.swapAxis_frame)
        self.scale_widget = QtGui.QWidget(self.alignSettingsGroupBox)
        self.scale_widget.setObjectName("scale_widget")
        self.gridLayout_4 = QtGui.QGridLayout(self.scale_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scaleRatio_lineEdit = QtGui.QLineEdit(self.scale_widget)
        self.scaleRatio_lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleRatio_lineEdit.sizePolicy().hasHeightForWidth())
        self.scaleRatio_lineEdit.setSizePolicy(sizePolicy)
        self.scaleRatio_lineEdit.setObjectName("scaleRatio_lineEdit")
        self.gridLayout_4.addWidget(self.scaleRatio_lineEdit, 1, 0, 1, 1)
        self.scaleRatio_label = QtGui.QLabel(self.scale_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleRatio_label.sizePolicy().hasHeightForWidth())
        self.scaleRatio_label.setSizePolicy(sizePolicy)
        self.scaleRatio_label.setObjectName("scaleRatio_label")
        self.gridLayout_4.addWidget(self.scaleRatio_label, 0, 0, 1, 1)
        self.scaleRatio_pushButton = QtGui.QPushButton(self.scale_widget)
        self.scaleRatio_pushButton.setEnabled(False)
        self.scaleRatio_pushButton.setObjectName("scaleRatio_pushButton")
        self.gridLayout_4.addWidget(self.scaleRatio_pushButton, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 2, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.scale_widget)
        self.resetButton_widget = QtGui.QWidget(self.alignSettingsGroupBox)
        self.resetButton_widget.setObjectName("resetButton_widget")
        self.gridLayout_5 = QtGui.QGridLayout(self.resetButton_widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 5, 1, 1, 1)
        self.alignLoadSaveWidgets = QtGui.QWidget(self.resetButton_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLoadSaveWidgets.sizePolicy().hasHeightForWidth())
        self.alignLoadSaveWidgets.setSizePolicy(sizePolicy)
        self.alignLoadSaveWidgets.setObjectName("alignLoadSaveWidgets")
        self.gridLayout = QtGui.QGridLayout(self.alignLoadSaveWidgets)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.loadSettingsButton = QtGui.QPushButton(self.alignLoadSaveWidgets)
        self.loadSettingsButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSettingsButton.sizePolicy().hasHeightForWidth())
        self.loadSettingsButton.setSizePolicy(sizePolicy)
        self.loadSettingsButton.setObjectName("loadSettingsButton")
        self.gridLayout.addWidget(self.loadSettingsButton, 0, 2, 1, 1)
        self.saveSettingsButton = QtGui.QPushButton(self.alignLoadSaveWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSettingsButton.sizePolicy().hasHeightForWidth())
        self.saveSettingsButton.setSizePolicy(sizePolicy)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.gridLayout.addWidget(self.saveSettingsButton, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.alignLoadSaveWidgets, 2, 0, 1, 2)
        self.verticalLayout_7.addWidget(self.resetButton_widget)
        self.verticalLayout_5.addWidget(self.alignSettingsGroupBox)
        self.reset_frame = QtGui.QFrame(self.alignPage)
        self.reset_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.reset_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.reset_frame.setObjectName("reset_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.reset_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.alignResetButton = QtGui.QPushButton(self.reset_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignResetButton.sizePolicy().hasHeightForWidth())
        self.alignResetButton.setSizePolicy(sizePolicy)
        self.alignResetButton.setObjectName("alignResetButton")
        self.horizontalLayout_3.addWidget(self.alignResetButton)
        self.verticalLayout_5.addWidget(self.reset_frame)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.toolBox.addItem(self.alignPage, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAllButton = QtGui.QPushButton(self.frame)
        self.viewAllButton.setObjectName("viewAllButton")
        self.horizontalLayout_2.addWidget(self.viewAllButton)
        self.doneButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_2.addWidget(self.doneButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.sceneviewerWidget = BaseSceneviewerWidget(ScaffoldRigidAlignerWidget, shared_opengl_context)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewerWidget.sizePolicy().hasHeightForWidth())
        self.sceneviewerWidget.setSizePolicy(sizePolicy)
        self.sceneviewerWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.sceneviewerWidget.setObjectName("sceneviewerWidget")
        self.horizontalLayout.addWidget(self.sceneviewerWidget)
        self.overlaySceneviewerWidget = BaseSceneviewerWidget(ScaffoldRigidAlignerWidget, shared_opengl_context)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlaySceneviewerWidget.sizePolicy().hasHeightForWidth())
        self.overlaySceneviewerWidget.setSizePolicy(sizePolicy)
        self.overlaySceneviewerWidget.setMinimumSize(QtCore.QSize(725, 0))
        self.overlaySceneviewerWidget.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.overlaySceneviewerWidget.setObjectName("overlaySceneviewerWidget")
        self.horizontalLayout.addWidget(self.overlaySceneviewerWidget)

        self.retranslateUi(ScaffoldRigidAlignerWidget)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(ScaffoldRigidAlignerWidget)

    def retranslateUi(self, ScaffoldRigidAlignerWidget):
        ScaffoldRigidAlignerWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Scaffold Rigid Aligner", None, QtGui.QApplication.UnicodeUTF8))
        self.timeData_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Is data recorded over time?", None, QtGui.QApplication.UnicodeUTF8))
        self.timeNo_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.timeYes_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.timePoint_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Time-point:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeSkip_pushButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Confirm and Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.partialY_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.partialX_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.partial_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Is data cloud partial?", None, QtGui.QApplication.UnicodeUTF8))
        self.partialZ_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.visualAid_checkBox.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Visual aid", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldY_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldAxis_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Scaffold UP axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldZ_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldX_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.dataZ_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.datadY_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAxis_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Data UP axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataX_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.yaw_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.roll_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.axisDone_pushButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Apply Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.upsideDown_checkBox.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Flip", None, QtGui.QApplication.UnicodeUTF8))
        self.rotateAxis_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Rotation (Euler angles):", None, QtGui.QApplication.UnicodeUTF8))
        self.upsideDown_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Is UP axis upside down?", None, QtGui.QApplication.UnicodeUTF8))
        self.pitch_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleRatio_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Scaffold to data scale ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleRatio_pushButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettingsButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Load pre-saved alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettingsButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Offset the model to the centre of the data points. May need to click View All afterwards.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Reset the alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.alignPage), QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Adjust the view to see the whole model", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Finish this step", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
