# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaffoldrigidalignerwidget.ui'
#
# Created: Tue Jun 18 14:55:09 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScaffoldRigidAlignerWidget(object):
    def setupUi(self, ScaffoldRigidAlignerWidget):
        ScaffoldRigidAlignerWidget.setObjectName("ScaffoldRigidAlignerWidget")
        ScaffoldRigidAlignerWidget.resize(1957, 998)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScaffoldRigidAlignerWidget.sizePolicy().hasHeightForWidth())
        ScaffoldRigidAlignerWidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(ScaffoldRigidAlignerWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(ScaffoldRigidAlignerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(410, 135))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 408, 956))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.alignPage = QtGui.QWidget()
        self.alignPage.setGeometry(QtCore.QRect(0, 0, 404, 892))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignPage.sizePolicy().hasHeightForWidth())
        self.alignPage.setSizePolicy(sizePolicy)
        self.alignPage.setObjectName("alignPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.alignPage)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.alignSettingsGroupBox = QtGui.QGroupBox(self.alignPage)
        self.alignSettingsGroupBox.setObjectName("alignSettingsGroupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.alignSettingsGroupBox)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.swapAxis_frame = QtGui.QFrame(self.alignSettingsGroupBox)
        self.swapAxis_frame.setMinimumSize(QtCore.QSize(0, 59))
        self.swapAxis_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.swapAxis_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.swapAxis_frame.setObjectName("swapAxis_frame")
        self.gridLayout_6 = QtGui.QGridLayout(self.swapAxis_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scaffoldX_radioButton = QtGui.QRadioButton(self.swapAxis_frame)
        self.scaffoldX_radioButton.setObjectName("scaffoldX_radioButton")
        self.gridLayout_6.addWidget(self.scaffoldX_radioButton, 1, 5, 1, 1)
        self.rotateAxis_label = QtGui.QLabel(self.swapAxis_frame)
        self.rotateAxis_label.setObjectName("rotateAxis_label")
        self.gridLayout_6.addWidget(self.rotateAxis_label, 6, 0, 1, 2)
        self.scaffoldAxis_label = QtGui.QLabel(self.swapAxis_frame)
        self.scaffoldAxis_label.setObjectName("scaffoldAxis_label")
        self.gridLayout_6.addWidget(self.scaffoldAxis_label, 1, 0, 1, 1)
        self.scaffoldY_radioButton = QtGui.QRadioButton(self.swapAxis_frame)
        self.scaffoldY_radioButton.setObjectName("scaffoldY_radioButton")
        self.gridLayout_6.addWidget(self.scaffoldY_radioButton, 1, 4, 1, 1)
        self.scaffoldZ_radioButton = QtGui.QRadioButton(self.swapAxis_frame)
        self.scaffoldZ_radioButton.setObjectName("scaffoldZ_radioButton")
        self.gridLayout_6.addWidget(self.scaffoldZ_radioButton, 1, 3, 1, 1)
        self.dataX_radioButton = QtGui.QRadioButton(self.swapAxis_frame)
        self.dataX_radioButton.setObjectName("dataX_radioButton")
        self.gridLayout_6.addWidget(self.dataX_radioButton, 2, 5, 1, 1)
        self.dataZ_radioButton = QtGui.QRadioButton(self.swapAxis_frame)
        self.dataZ_radioButton.setObjectName("dataZ_radioButton")
        self.gridLayout_6.addWidget(self.dataZ_radioButton, 2, 3, 1, 1)
        self.dataY_radioButton = QtGui.QRadioButton(self.swapAxis_frame)
        self.dataY_radioButton.setObjectName("dataY_radioButton")
        self.gridLayout_6.addWidget(self.dataY_radioButton, 2, 4, 1, 1)
        self.dataAxis_label = QtGui.QLabel(self.swapAxis_frame)
        self.dataAxis_label.setObjectName("dataAxis_label")
        self.gridLayout_6.addWidget(self.dataAxis_label, 2, 0, 1, 1)
        self.upsideDown_label = QtGui.QLabel(self.swapAxis_frame)
        self.upsideDown_label.setObjectName("upsideDown_label")
        self.gridLayout_6.addWidget(self.upsideDown_label, 4, 0, 1, 1)
        self.yaw_doubleSpinBox = QtGui.QDoubleSpinBox(self.swapAxis_frame)
        self.yaw_doubleSpinBox.setObjectName("yaw_doubleSpinBox")
        self.gridLayout_6.addWidget(self.yaw_doubleSpinBox, 7, 3, 1, 1)
        self.yaw_label = QtGui.QLabel(self.swapAxis_frame)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout_6.addWidget(self.yaw_label, 6, 3, 1, 1)
        self.pitch_doubleSpinBox = QtGui.QDoubleSpinBox(self.swapAxis_frame)
        self.pitch_doubleSpinBox.setObjectName("pitch_doubleSpinBox")
        self.gridLayout_6.addWidget(self.pitch_doubleSpinBox, 7, 4, 1, 1)
        self.pitch_label = QtGui.QLabel(self.swapAxis_frame)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout_6.addWidget(self.pitch_label, 6, 4, 1, 1)
        self.roll_doubleSpinBox = QtGui.QDoubleSpinBox(self.swapAxis_frame)
        self.roll_doubleSpinBox.setObjectName("roll_doubleSpinBox")
        self.gridLayout_6.addWidget(self.roll_doubleSpinBox, 7, 5, 1, 1)
        self.roll_label = QtGui.QLabel(self.swapAxis_frame)
        self.roll_label.setObjectName("roll_label")
        self.gridLayout_6.addWidget(self.roll_label, 6, 5, 1, 1)
        self.upsideDown_checkBox = QtGui.QCheckBox(self.swapAxis_frame)
        self.upsideDown_checkBox.setObjectName("upsideDown_checkBox")
        self.gridLayout_6.addWidget(self.upsideDown_checkBox, 4, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.swapAxis_frame)
        self.alignLoadSaveWidgets = QtGui.QWidget(self.alignSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLoadSaveWidgets.sizePolicy().hasHeightForWidth())
        self.alignLoadSaveWidgets.setSizePolicy(sizePolicy)
        self.alignLoadSaveWidgets.setObjectName("alignLoadSaveWidgets")
        self.gridLayout = QtGui.QGridLayout(self.alignLoadSaveWidgets)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.saveSettingsButton = QtGui.QPushButton(self.alignLoadSaveWidgets)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.gridLayout.addWidget(self.saveSettingsButton, 0, 0, 1, 1)
        self.loadSettingsButton = QtGui.QPushButton(self.alignLoadSaveWidgets)
        self.loadSettingsButton.setEnabled(True)
        self.loadSettingsButton.setObjectName("loadSettingsButton")
        self.gridLayout.addWidget(self.loadSettingsButton, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.alignLoadSaveWidgets)
        self.verticalLayout_5.addWidget(self.alignSettingsGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.alignResetButton = QtGui.QPushButton(self.alignPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignResetButton.sizePolicy().hasHeightForWidth())
        self.alignResetButton.setSizePolicy(sizePolicy)
        self.alignResetButton.setObjectName("alignResetButton")
        self.verticalLayout_5.addWidget(self.alignResetButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.toolBox.addItem(self.alignPage, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAllButton = QtGui.QPushButton(self.frame)
        self.viewAllButton.setObjectName("viewAllButton")
        self.horizontalLayout_2.addWidget(self.viewAllButton)
        self.doneButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_2.addWidget(self.doneButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.sceneviewerWidget = BaseSceneviewerWidget(ScaffoldRigidAlignerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewerWidget.sizePolicy().hasHeightForWidth())
        self.sceneviewerWidget.setSizePolicy(sizePolicy)
        self.sceneviewerWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.sceneviewerWidget.setObjectName("sceneviewerWidget")
        self.horizontalLayout.addWidget(self.sceneviewerWidget)
        self.overlaySceneviewerWidget = BaseSceneviewerWidget(ScaffoldRigidAlignerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overlaySceneviewerWidget.sizePolicy().hasHeightForWidth())
        self.overlaySceneviewerWidget.setSizePolicy(sizePolicy)
        self.overlaySceneviewerWidget.setMinimumSize(QtCore.QSize(750, 0))
        self.overlaySceneviewerWidget.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.overlaySceneviewerWidget.setObjectName("overlaySceneviewerWidget")
        self.horizontalLayout.addWidget(self.overlaySceneviewerWidget)

        self.retranslateUi(ScaffoldRigidAlignerWidget)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(ScaffoldRigidAlignerWidget)

    def retranslateUi(self, ScaffoldRigidAlignerWidget):
        ScaffoldRigidAlignerWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Scaffold Rigid Aligner", None, QtGui.QApplication.UnicodeUTF8))
        self.alignSettingsGroupBox.setTitle(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Scaffold alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldX_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.rotateAxis_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Euler orientation:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldAxis_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Scaffold UP axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldY_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.scaffoldZ_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.dataX_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.dataZ_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.dataY_radioButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.dataAxis_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Data UP axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.upsideDown_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Is UP axis upside down?", None, QtGui.QApplication.UnicodeUTF8))
        self.yaw_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.pitch_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.roll_label.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.upsideDown_checkBox.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Flip", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Offset the model to the centre of the data points. May need to click View All afterwards.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettingsButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Load pre-saved alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettingsButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Reset the alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.alignPage), QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Initial Rigid Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Adjust the view to see the whole model", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setToolTip(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Finish this step", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("ScaffoldRigidAlignerWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
